### ISSUE TITLE
add preview function to marks

### ISSUE THREAD

**Issue by Cloudprogram** [Yggdroot/LeaderF-marks#2]
The preview function in Leaderf is very convenience.Can you merge it in LeaderF-marks?
Thanks!

**Comment by Cloudprogram** [comment]
There is something unexpected in the preview function。When i don‘t save the file，the preview function would show some information like error！
The information is whether you add to remind us to save the files or just a bug？
Can you add the setting when i close the preview function，the original file come back not the file previewed。Most people would like to reserve original file there。

![QQ截图20190512181537](https://user-images.githubusercontent.com/49339934/57581103-44ac8300-74e5-11e9-97a8-3b0dd600ea40.png)

**Comment by Yggdroot** [comment]
Could you explain the exact steps to reproduce this issue ?

**Comment by Cloudprogram** [comment]
> Could you explain the exact steps to reproduce this issue ?

first：edit file without saving
second： jump into marks with TAB button after calling LeaderfMarks ；
last：preview the marks with p button 
After these process，you would see such information like the picture below：
![QQ截图20190512181537](https://user-images.githubusercontent.com/49339934/57582484-fb196380-74f7-11e9-9201-9fd3dc968d11.png)

**Comment by Yggdroot** [comment]
Sorry, I still can not reproduce this issue.

**Comment by Yggdroot** [comment]
Got it. The mark you are previewing is in another file.

You should `set hidden` in your vimrc.

**Comment by Cloudprogram** [comment]
> Sorry, I still can not reproduce this issue.

Maybe you can use the vim that i‘m using to reproduce。

链接：https://pan.baidu.com/s/18XTzvI0mss6IvH-R6iRcQw 
提取码：sjbh 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Cloudprogram** [comment]
> Got it. The mark you are previewing is in another file.
> 
> You should `set hidden` in your vimrc.

yes，you are right。
when i preview different file，the information would appear。

**Comment by Cloudprogram** [comment]
> Got it. The mark you are previewing is in another file.
> 
> You should `set hidden` in your vimrc.

You should set hidden in your vimrc.
what do you mean？
Then the different file that i can't preview，or just hide the information to remind to save file？

**Comment by Yggdroot** [comment]
Add `set hidden` in your vimrc file.

**Comment by Cloudprogram** [comment]
> Add `set hidden` in your vimrc file.

what 

> set hidden

**Comment by Cloudprogram** [comment]
> Add `set hidden` in your vimrc file.

set hidden " 允许在有未保存的修改时切换缓冲区，此时的修改由 vim 负责保存
Thanks！
